### ISSUE TITLE
[Crash]: auto-terraforming tool crashes when connected to vanilla server

### ISSUE THREAD

**Issue by Loafdude** [citymania-org/cmclient#15]
### Version of OpenTTD

13.0 on Windows 11

### Steps to reproduce

To reproduce, enable auto-terraforming and use on online server (tried two different servers)
poly tool works without terraforming on these servers.
Auto-terraforming also works in a local game.

### Upload crash files

[OpenTTD_terraforming_crash.zip](https://github.com/citymania-org/cmclient/files/10985941/OpenTTD_terraforming_crash.zip)

**Comment by ldpl** [comment]
Should be fixed in e4a84ec, will be included in the next release.
