### ISSUE TITLE
[Crash]: In rare cases when using the station tool

### ISSUE THREAD

**Issue by Rau117** [citymania-org/cmclient#17]
### Version of OpenTTD

Citymania 13.1 Apr 11 release; windows 10

### Steps to reproduce

I'm not sure how to reproduce this crash, I did not succeed to repeat this in a single game. And even in a different place on the same save, there are no crashes. But in a particular place, the game constantly crashes, mostly without an error message.

This is not an isolated case, earlier similar crashes also appeared when using the station like _older crash.zip_, but this one does not have a save.

https://github.com/citymania-org/cmclient/assets/47086324/f8916a4a-1b84-460b-a44b-6200d8888e92

### Upload crash files

[current crash.zip](https://github.com/citymania-org/cmclient/files/11523247/citymania.crash.zip)
[older crash.zip](https://github.com/citymania-org/cmclient/files/11523260/older.crash.zip)

**Comment by ldpl** [comment]
@Rau117 can you attach a save file here? The one in the zip is empty.

**Comment by Rau117** [comment]
_Didn't pay attention that the save was 0 kb._

[just another crash.zip](https://github.com/citymania-org/cmclient/files/11710758/just.another.crash.zip)
