### ISSUE TITLE
[Bug]: Watch company actions - redundant windows on click

### ISSUE THREAD

**Issue by Rau117** [citymania-org/cmclient#18]
### Version of OpenTTD

Citymania 13.2 Windows 10

### Expected result

When clicking on the «Watch company actions» in the top menu, appears only one window

### Actual result

With a single click, 3 windows open at once.
However, if you hold down the mouse button and select a company from the list, everything works correctly.

https://github.com/citymania-org/cmclient/assets/47086324/5f59603d-4cdb-43cf-805e-ede2e4eeaea9

### Steps to reproduce

1. Load the game
2. Click on 4 arrows / eye on top menu

**Comment by ldpl** [comment]
I can't reproduce this. Is it still happening in 13.4?
