### ISSUE TITLE
[Bug]: Unable to set login passwords longer than 31 characters

### ISSUE THREAD

**Issue by danidoedel** [citymania-org/cmclient#19]
### Version of OpenTTD

13.3

### Expected result

It should be possible to set community (citymania, n-ice, btpro) login passwords longer than 31 characters.

### Actual result

Tested this with the citymania login. If a password longer than 31 characters is set via gui it will be truncated to 31 characters and the login will fail. Login via the `!login` command works fine for longer passwords.

### Steps to reproduce

1. Set a password longer than 31 characters via the gui
2. Click login
3. Login will fail and a truncated password will be displayed in the chat
4. Alternatively open the password gui again which will also show the truncated password

**Comment by ldpl** [comment]
Increased to 127
