### ISSUE TITLE
[Bug]: CityMania client v13.4 failed to release

### ISSUE THREAD

**Issue by Ministorm3** [citymania-org/cmclient#22]
### Version of OpenTTD

13.4

### Expected result

Expected to be able to download v13.4 of CityMania.

### Actual result

It appears the linux build failed and the client did not release.
https://github.com/citymania-org/cmclient/actions/runs/5716879439

I am hoping you are already aware of the issue. But, in case you aren't, this is my attempt to notify you. :)

### Steps to reproduce

1. Try to download v13.4
2. Become sad when it isn't available for download

(feel free to close this case if you already know about this)

**Comment by ldpl** [comment]
Thanks for your efforts but it was kind of intentional.
I wasn't able to release 13.4 immediately and now I decided to take a few more days to get some fixes in.
