### ISSUE TITLE
Unable to join company within the server

### ISSUE THREAD

**Issue by danidoedel** [citymania-org/cmclient#3]
## Version of OpenTTD
1.11

## Expected result
If I click on "Password" in the company window the password window should open so I can join a company.

## Actual result
Clicking on "Password" does nothing. Vanilla OpenTTD works as expected and I can also join a company directly with joining the server.

## Steps to reproduce
Join a server as watcher and try to join a company.

**Comment by ldpl** [comment]
Yeah, there is that, unfortunately. You can still join from the server lobby but not in game, will fix in the next release (that will be soon enough).

**Comment by ldpl** [comment]
Fixed in 0f8af6108d082ccedf3f1f6910ddd4fe405a26ad
