### ISSUE TITLE
[Bug]: Cargo-Payment-Rates-Graph has vanilla values

### ISSUE THREAD

**Issue by mariocvj** [citymania-org/cmclient#38]
### Version of OpenTTD

Citymania-client-14.1-windows-win64

### Expected result

I attached the screenshot of the graph from Citymania v13.4 which does not have this bug, notice the Goods and Valuables dropoff is at 80 days.
![image](https://github.com/user-attachments/assets/7086980c-722e-4671-84ee-d170772433ed)

### Actual result

Lines drawn on the graph are same as official OpenTTD version despite the numbers on days-in-transit axis being doubled.
I attached the screenshot of the Citymania v14.1, notice the Goods and Valuables dropoff is at 160 days.
![actualResult](https://github.com/user-attachments/assets/93d38c81-e0e5-4532-a4e9-d75b094903cb)

### Steps to reproduce

The bug occurs to me consistently every time I play on v14.1 of Citymania client.
Besides vanilla OpenTTD, I also tested using FIRS and the bug is still there with moded resources.

**Comment by ladysadie** [comment]
![cm_13 4](https://github.com/user-attachments/assets/0b214673-9daa-4ac5-9577-91fa59b9821d)
Even in the 13.4 version code this graph is actually  pretty misleading. It is telling the user it's displaying values from 20 ticks up to 480 ticks.

The data it's actually calculating is way different. It starts at 8 ticks and goes to 192 ticks.

**Comment by ladysadie** [comment]
Fixing the calculations isn't a hard fix.  It kind of breaks the graph though:

![14 1_fixed](https://github.com/user-attachments/assets/c47b3aaa-d0a9-4e9a-97b6-ae748fbe9b26)

**Comment by ladysadie** [comment]
Okay changing the amount of cargo or the distance didn't change the data.  It just scaled the Y axis labels accordingly.

**Comment by ladysadie** [comment]
Dropping the number of steps makes the differences easier to see:

![maybe](https://github.com/user-attachments/assets/ce1c9155-338d-4c47-9391-7279de44d656)

**Comment by ldpl** [comment]
> Even in the 13.4 version code this graph is actually pretty misleading. It is telling the user it's displaying values from 20 ticks up to 480 ticks.
> The data it's actually calculating is way different. It starts at 8 ticks and goes to 192 ticks.

X axis on the chart is in days and afaict it calculates them correctly. You were probably confuled by GetTransportedGoodsIncome taking transfer periods which are 2.5 days each.
