### ISSUE TITLE
Tooltip of "Login Window" hard to read

### ISSUE THREAD

**Issue by danidoedel** [citymania-org/cmclient#4]
## Version of OpenTTD
1.11

## Expected result
Tooltip font of "Login Window" should have a different color to be better readable

## Actual result
Tooltip is hard to read

<img width="273" alt="image" src="https://user-images.githubusercontent.com/10995998/113617656-cb8e1a00-9680-11eb-93a9-1d71e7182e44.png">

@ldpl I am wondering why I can't click on the CityMania button to log in. The other communities seem to work. Is this intended?

**Comment by danidoedel** [comment]
Btw the password here is also quite hard to read. Didn't want to open a new issue for that:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/10995998/113619331-07c27a00-9683-11eb-8df9-ba011e0e0a1f.png">

**Comment by ldpl** [comment]
Fixed all 3 of the mentioned issues
